### ISSUE TITLE
Getting an error when going to Kernel

### ISSUE THREAD

**Issue by drskoolie** [ipselium/cpyvke#2]
Python: 3.8.2

OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Nvim:
NVIM v0.5.0-dev

================================================================================
**When I switch to the Kernel view in cpyvke, I get this error.**

```
Exiting ! Closing cpyvke...
Traceback (most recent call last):
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/objects/panel.py", line 106, in display
    self.tasks()
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/curseswin/app.py", line 77, in wrapper
    function(*args, **kwargs)
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/objects/panel.py", line 120, in tasks
    self.app.kernel_win.display()
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/objects/panel.py", line 436, in display
    self.tasks()
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/curseswin/app.py", line 77, in wrapper
    function(*args, **kwargs)
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/objects/panel.py", line 478, in tasks
    self.refresh()
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/objects/panel.py", line 501, in refresh
    self.app.status_bar()
  File "/home/linux5mon/.local/lib/python3.8/site-packages/cpyvke/curseswin/app.py", line 243, in status_bar
    debug_info_id = 'kernel {} '.format(self.cf.split('-')[1].split('.')[0])
IndexError: list index out of range
```

**Comment by ipselium** [comment]
Indeed, the new versions of jupyter use a different path for kernels. I will fix this ASAP.

**Comment by drskoolie** [comment]
Thanks!

Your variable explorer is the best one that I have seen. By far.

**Comment by ipselium** [comment]
Bug Fixed.
